public static void main(String[] args) {
        System.out.println("Imprimir nombre y edad");
        String name="David";
        int edad=15;
        System.out.println(name);
        System.out.println(edad);

        System.out.println("suma de dos numeros");
        int a=5;
            int b=3;
            int suma=a+b;
        System.out.println(suma);

        System.out.println("Resta de dos numeros");
        int f=15;
        int v=10;
        int resta=f-v;
        System.out.println(resta);

        System.out.println("Multiplicar dos numeros");
        int x=7;
         int y=8;
         long multiplicacion=x*y;
        System.out.println(multiplicacion);

        System.out.println("Division de dos numeros");
        int valor1=27;
        int valor2=3;
        int division=valor1/valor2;
        System.out.println(division);

        System.out.println("Calcular el cuadrado de un numero");
        int cuadrado=a*a;
        System.out.println(cuadrado);

        System.out.println("Celcius a Fahrenheit");
        double celcius=(58.98);
        double fahrenheit=((celcius) * (1.8) + 32);
        System.out.println(fahrenheit);

        System.out.println("Perimetro de un rectangulo");
            int LADO1=6;
            int LADO2=8;
            int perimetro=(2*LADO1) + (2*LADO2);
            System.out.println(perimetro);

        System.out.println("Area de un circulo");
        double radio=5.7;
        double Area= (3.14) * (radio*radio);
        System.out.println(Area);

        System.out.println("Años a Dias");
        int años=3;
        int dias=365;
        int resultado= dias*años;
        System.out.println(resultado);

        System.out.println("El doble y el triple de un numero");
        int one=7;
            int doble=2;
        int triple=3;
        System.out.println(one*doble);
        System.out.println(one*triple);

      System.out.println("Kilometros a metros y centimetros");
        long km=9;
        long M=1000;
        System.out.println(km*M);
        long m=85;
        long cm=100;
        System.out.println(m*cm);

        System.out.println("Area y perimetro de un cuadrado");
        int lado=7;
        int area=lado*lado;
        System.out.println(area);
        int periMetro=lado+lado+lado+lado;
        System.out.println(periMetro);

        System.out.println("volumen de un cubo");
        int Lado=9;
        int Cubo=Lado*Lado*Lado;
        System.out.println(Cubo);

        System.out.println("Volumen de una esfera");
        double voLumen=(1.3) * (3.14) *(radio*radio*radio);
        System.out.println(voLumen);

        System.out.println("Sumar los tres numeros naturales");
        long w=1;
            long z=2;
            long V=3;
        long Suma=w+z+V;
        System.out.println(Suma);
            
        System.out.println("Calcular el descuento aplicado a una compra, precio y porcentaje");
        double compra=70000;
        double desCuento=0.30;
        double total=compra*desCuento;
            System.out.println(total);

        System.out.println("Calcular la propina a dejar en un restaurante");
        double comida=100000;
        double porCentaje=0.20;
        double propinA=comida*porCentaje;
        System.out.println(propinA);

        double Propina=20000.0;
        double Total=comida+Propina;
        System.out.println(Total);
        
    }
}